Fix jsp-file handling
piranhacloud/piranha pull request #1960
Opened 2021-10-11 17:50 UTC by folker-kuhn

Fixes #1959

This will fix the jsp-file handling. It moved the wasp extension to right location and removed code that was not needed.

2021-10-11 22:49 UTC, mnriem commented
See #1959

2021-10-13 12:41 UTC, Thihup approved these changes
LGTM

2021-10-13 13:11 UTC, mnriem commented on extension/server/src/main/java/cloud/piranha/extension/server/ServerExtension.java
> +        // WaspExtension must be added before WebXmlExtension, so webApplication.addJspFile that's called by WebXmlExtension
Now that you have solved the ordering problem can you remove the comment?

2021-10-13 13:13 UTC, mnriem requested changes
Just remove the one comment and then you are good to go. Thank YOU!

2021-10-13 15:24 UTC, mnriem approved these changes

2021-10-13 15:36 UTC, merged

2021-10-13 15:36 UTC, mnriem commented
@folker-kuhn Thank you for this contribution!